export type Env = {
	ENV_SERVER_URL?: string

	ENV_WIDGET_API_ENDPOINT_DEV?: string
	ENV_WIDGET_API_ENDPOINT_PROD?: string
	ENV_WIDGET_API_ENDPOINT_TEST?: string

	ENV_INTEGRATION_NAME_PROD?: string
	ENV_INTEGRATION_NAME_DEV?: string
	ENV_INTEGRATION_NAME_TEST?: string

	ENV_WEBSOCKET_ENDPOINT_DEV?: string
	ENV_WEBSOCKET_ENDPOINT_PROD?: string
	ENV_WEBSOCKET_ENDPOINT_TEST?: string


}